schemaVersion: 2.2.0
metadata:
  name: l0rd-blog
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:latest
      memoryRequest: 1Gi
      memoryLimit: 8Gi
      cpuLimit: '4'
      cpuRequest: '0.5'
commands:
  - id: yarn-install
    exec:
      component: tools
      commandLine: yarn install
  - id: yarn-dev
    exec:
      component: tools
      commandLine: yarn dev
